apiVersion: v1
kind: PersistentVolume
metadata:
    name: persistent-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/data