apiVersion: v1
kind: Service
metadata:
  name: visualizer-nodeport-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: visualizer #select the pod/pods
  type: NodePort